version: '3.8'

services:
  web:
    image: python:3.12
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5000"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"